// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:33297bfc-5703-4b92-a451-118761239761",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_YOYuSlQWb", // cognito9e1a3ca5_userpool_9e1a3ca5
    "aws_user_pools_web_client_id": "3keiqum1rktvprs8avnq8vq1r1"
    // "aws_user_pools_id": "us-east-1_NgmRin3Ld", // cognito9e1a3ca5_userpool_9e1a3ca5
    // "aws_user_pools_web_client_id": "4fps0oee7f0ablfb14gqfmig83"
};


export default awsmobile;
